### ISSUE TITLE
Implement `DoubleEndedIterator` for `Powerset`

### ISSUE THREAD

**Issue by TennyZhuang** [rust-itertools/itertools#905] opened 2024-03-18 09:44 UTC

**Comment by Philippe-Cholet** [comment] 2024-03-18 09:52
Duplicate of #620 which contains arguments on why it's not implemented.

**Comment by TennyZhuang** [comment] 2024-03-18 10:05
> Duplicate of #620 which contains arguments on why it's not implemented.

Ok, I just take a look at the implementation and the explanation seems good to me.

Generally, if we use a bitwise-based implementation, I guess the `rev` can be implemented in a naive solution?

**Comment by Philippe-Cholet** [comment] 2024-03-18 10:12
No matter the implementation or the iterator, support a `DoubleEndedIterator` implementation can have some cost to store backward informations (and not just forward ones).

But I guess that if you use a bitwise implementation (which is surely lightweight) then the cost would probably be quite small and more acceptable for you than here for us.

**Closed** 2024-03-22 08:16 UTC
